const PhotosActionTypes = {
  FETCH_PHOTOS_START: 'FETCH_PHOTO_START',
  FETCH_PHOTOS_SUCCESS: 'FETCH_PHOTO_SUCCESS',
  FETCH_PHOTOS_FAILURE: 'FETCH_PHOTO_FAILURE',
  SEARCH_PHOTOS: 'SEARCH_PHOTOS',
};

export default PhotosActionTypes;
